### ISSUE TITLE
撮影依頼のJsonファイルの仕様を決める。

### ISSUE THREAD

**Issue by yamaKyo** [Smart-SE/sse2019-group1#24]
写真の送り先とreq_id(社員名)は必須

**Comment by makotookamura** [comment]
{
    'req_type': 'take_photo',
    's3_bucket': 'xxxx'
}

**Comment by yamaKyo** [comment]
{ "req_type": "take_photo",
"s3_bucket": "xxxx" 
}
Jsonはシングルクォーテーションを使えないので、ダブルクォーテーションにして下さい。

**Comment by k08n** [comment]
下記で実装、動作を確認したのでclose

{
 "req_type": "take_photo"
}
