### ISSUE TITLE
画像を送信する前に先にメッセージだけ返信する

### ISSUE THREAD

**Issue by makotookamura** [Smart-SE/sse2019-group1#36]
田渕さんの文字おこしくんでもそうなっていると思うのですが、画像を送信する前に先にメッセージだけ反応してあげたほうが親切な気がしました。（冷蔵庫を覗きにいくから10秒くらい待っててね！的な）。ShouldかCouldくらいの要件ですが、可能であれば！

**Comment by hiromasat** [comment]
私の作った文字起こしちゃんはLINE Messaging APIの機能で設定しました。

replyTokenが有効なのは1回のみ？2回使えるですかね。

<img width="996" alt="スクリーンショット 2019-07-11 20 08 05" src="https://user-images.githubusercontent.com/16264266/61048749-b6d61100-a41d-11e9-856a-14587a6f760b.png">

**Comment by makotookamura** [comment]
ありがとうございます。なるほど。
たしかに1回のみだった気がする。（2回送るなら、reply+sendでやらなきゃいけなかった気がする）

田渕さんの真似してやってみます！

**Comment by makotookamura** [comment]
Line側に設定済み。あとは全体動かしてみて文言調整。
