### ISSUE TITLE
冷蔵庫にあるものを遠隔から確認する

### ISSUE THREAD

**Issue by yamaKyo** [Smart-SE/sse2019-group1#39]
開発したIoTシステムの感想をどうぞ

**Comment by enPitSmartSE** [comment]
周囲の方とのSkill差を実感しました。残りのSmart SEの受講期間も精進したいと思います。

**Comment by hiromasat** [comment]
離れた場所から冷蔵庫の中身の写真が見えるだけでも、非常に便利と感じた。将来的には、卵ある？牛乳はあと何本残っている？などの会話ができるとさらに有効な機能と感じた。後付けカメラという観点も今の冷蔵庫が使えて良い。

**Comment by yamaKyo** [comment]
よく調味料を複数買いしていまうことがあり、あったら便利と感じた。また、この話は冷蔵庫以外にも、書籍の管理などにも使えると感じた

**Comment by k08n** [comment]
冷蔵庫の中身を遠隔から確認でき、便利だと感じた。
画像を用いたサービスなので、今後の拡張性に期待が持てる。

**Comment by enPitSmartSE** [comment]
思ったよりもクリアに中身を確認でき、非常に実用的だと感じた。
冷蔵庫だけでなく、シンクの下にも食料品を格納しているので、
複数のカメラを使用して食料品全体を管理してみたいと思った。

**Comment by Harold2030** [comment]
重複買いを防ぐことができ、今後の拡張性にとても期待ができる。

**Comment by hiromasat** [comment]
作ってみて、触ってみて、そしたらやっぱり良いね、もっとこうしたいというアイデアがたくさん出ました。多くの人が欲しいと共感する機能になりました。
