### ISSUE TITLE
チーム活動、スクラム開発についての感想

### ISSUE THREAD

**Issue by hiromasat** [Smart-SE/sse2019-group1#40]
チーム活動、スクラム開発についての感想をみなさん一言お願いします。

**Comment by hiromasat** [comment]
メンバーがそれぞれ得意分野、また知らない部分を調べてSlackを通して共有でき、協力できた実感がある。システムが動いたときは非常にうれしかった。

**Comment by k08n** [comment]
書こうと思ったらクローズしちゃいましたスイマセン

**Comment by yamaKyo** [comment]
普段は個人開発が多いので、チームで議論しながら開発するのは楽しかった。

**Comment by makotookamura** [comment]
未だ完全に作りきってない中での感想ですが。。

私も最近は個人開発かメンバーに開発をお願いすることが多いので、自らチームメンバーとして協力して開発する楽しさを再認識しました。

何故楽しさを感じたのかを自己分析すると、
ウォーターフォールや上下のある組織での開発では、計画時点でだいたいの落としどころをリーダーが頭の中に作ってしまいます。ですので、結果が出てもまぁ予想通りのものになりますし、逆に、期待値のギャップを調整することに（誰かが）苦労します。
一方、アジャイル（スクラム）では一人だと発想出来ないアイディア（＝不確実性）も取り入れながら限られた時間の中で実現可能な一番良い落としどころをメンバー全員で流れながら作っていく感じがします。その、分からないという不安を皆で乗り越えつつ、相互に期待しあい、期待に応えあう関係が楽しさの源泉なのではと思います。（今回はチームメンバーに恵まれたのもあると思いますが）

**Comment by enPitSmartSE** [comment]
基幹システムの開発などは実施していたが、今回はほとんどが初めて触れる技術になり、
先行して業務で対応しているほかのメンバーの方のスキルにかなり頼りきりになってしまった。
各所の技術に少しずつ触れることでこれから学習するきっかけができたので、自己研鑽に努めたい。

**Comment by Harold2030** [comment]
チームメンバーはそれぞれの役割を果たし、プロトタイプ開発がスムーズに進められたことを実感した。

**Comment by hiromasat** [comment]
みなさま振り返りありがとうございました。午前中に様々なアイデアが出てきて、それをすぐに実装に落とし込んでいただきありがとうございます。また資料も素早く直していただき、とても素晴らしいプロトタイプが作れました。すごく楽しかったです。
